# Generated by Django 3.2.5 on 2021-07-15 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ManyToManyField(db_table='grades_and_teachers', to='grades.Grade')),
                ('subject', models.ManyToManyField(db_table='teachers_and_subjects', to='subjects.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
