# Generated by Django 3.2.5 on 2021-08-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0002_alter_subject_options'),
        ('teachers', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='submitted_assignments')),
                ('submitted_on', models.DateField(null=True)),
                ('submitted', models.CharField(choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], default=('Not Submitted', 'Not Submitted'), max_length=30)),
                ('assignment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
