# Generated by Django 3.2.5 on 2021-08-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='assignment_name',
            new_name='assignment',
        ),
    ]
