# Generated by Django 3.2.5 on 2021-08-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20210830_0833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='assignmentsubmission',
            table='assignment_submissions',
        ),
    ]
