# Generated by Django 3.2.5 on 2021-08-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
