# Generated by Django 3.2.5 on 2021-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_rename_student_id_assignmentsubmission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], default=('Not Submitted', 'Not Submitted'), max_length=50),
        ),
    ]
