# Generated by Django 3.2.5 on 2021-08-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_assignmentsubmission_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted',
            field=models.CharField(default='Not Submitted', max_length=50),
        ),
    ]
