# Generated by Django 3.2.5 on 2021-08-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_no_of_students_grade_no_of_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade_name']},
        ),
    ]
